### PR TITLE
add tagging support, issue #15

### PR DESCRIPTION
**Pull request by u-fischer**
please check if I missed something. This requires a current LaTeX, so if sillypage should also work with older LaTeX some checks must be added additionally.

### CODE REVIEW

**Comment by cereda** [comment]
Thanks, Ulrike! All looks good. Just checking:

```
Running checks on
  sillypage001 (1/3)
  sillypage002 (2/3)
  sillypage003 (3/3)
          --> failed


  Check failed with difference files
  - ./build/test/sillypage003.pdftex.diff
 ```

Maybe we need to update one of the test files?

Thank you!

**Comment by u-fischer** [comment]
hm, not sure what local files I had on the other computer that changed the font number. I remade the test. Does it work for you now?

**Comment by cereda** [comment]
They do now, Ulrike! Thank you! I will proceed with the release! :rocket: :duck:

**Review by cereda — APPROVED** [review]
Update approved! :rocket:

**Review by PhelypeOleinik — APPROVED** [review]

**Pull request merged**
