### PR TITLE
Preparing for version 1.3

### PR DESCRIPTION
**Pull request by cereda**
In a nutshell:

- Raster image was replaced by its vector counterpart.
- `.dtx` was updated to reflect changes (I added some cropping from top and bottom, hope it's okay).
- Included the `.svg` in the repository.
- Updated a couple of stuff.

After merging, we just need to update the CHANGELOG and create the corresponding tag (and possibly change the release date, as I used a pessimistic ETA — two days from now). :wink:

### CODE REVIEW

**Comment by samcarter** [comment]
I'll make a new version of the image so clipping is not necessary.

**Comment by cereda** [comment]
@samcarter that would be helpful, thanks! If possible, just crop `7px` above and below from the current `.pdf` and we are good to go, I think. :wink:

**Comment by samcarter** [comment]
I just pushed a new version with 
```
\documentclass[multido=true]{standalone}
\usepackage{sillypage}

\begin{document}
\multido{\iA=1+1}{12}{%
\includegraphics[trim={0 7 0 7},clip]{silly_vector_\iA}%
}
\end{document}
```
to produce the multi-page document.

**Comment by cereda** [comment]
Thanks, then we can simplify `sillypage.dtx`, will do that.

**Review by samcarter — APPROVED** [review]

**Review by PhelypeOleinik — APPROVED** [review]

**Pull request merged**
